# Generated by Django 5.1.1 on 2024-11-04 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0002_alter_trip_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_date',
            new_name='arrival_date_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=400)),
                ('restaurant_date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=200)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_restaurant', to='trip_planner.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
