# Generated by Django 5.1.1 on 2024-11-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0004_activity_city_restaurant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_flight', to='trip_planner.category'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_hotel', to='trip_planner.category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_restaurant', to='trip_planner.category'),
        ),
    ]
